/**
 * Site-wide constants. Kept free of Vite-specific imports so the e2e tests can import it too.
 */

/** Section anchor ids, in page order. Navigation links and in-page buttons point at these. */
export const SECTION_IDS = {
  home: "home",
  about: "about",
  skills: "skills",
  projects: "projects",
  experience: "experience",
  education: "education",
  contact: "contact",
} as const;

export type SectionId = (typeof SECTION_IDS)[keyof typeof SECTION_IDS];

/** The CV PDF in public/, generated by cv-generator/generate.py. */
export const CV_FILENAME = "Victor-Laitila-Software-Engineer-CV.pdf";
