/**
 * Career data loader - loads data from career.json (generated by career-engine).
 * 
 * The portfolio reads from a single JSON file that career-engine writes
 * during the sync process. This keeps the portfolio in sync with the
 * canonical career.yaml source of truth.
 */

import type { CareerData, PortfolioExtensions } from './types';
import careerJson from './career.json';
import { portfolioExtensions } from './extensions';

const careerData = careerJson as CareerData;

/**
 * Get the full career data with portfolio extensions merged in.
 */
export function getCareerData(): CareerData {
  // Merge project assets from extensions
  const projectsWithAssets = careerData.projects.map(project => {
    const assets = portfolioExtensions.projectAssets[project.name];
    if (assets) {
      return { ...project, ...assets };
    }
    return project;
  });

  return {
    ...careerData,
    projects: projectsWithAssets,
  };
}

/**
 * Get portfolio-specific extensions (about section, project images, etc.)
 */
export function getPortfolioExtensions(): PortfolioExtensions {
  return portfolioExtensions;
}

export { careerData, portfolioExtensions };
export type { CareerData, PortfolioExtensions } from './types';
